import { Fragment } from "react"

export const April2023 = () => {
    return (
        <Fragment>
            <section>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li>1</li>
                <li>2</li>
            </section>
            <section>
                <li>3</li>
                <li>4</li>
                <li>5</li>
                <li>6</li>
                <li>7</li>
                <li>8</li>
                <li>9</li>
            </section>
            <section>
                <li>10</li>
                <li>11</li>
                <li>12</li>
                <li>13</li>
                <li>14</li>
                <li>15</li>
                <li>16</li>
            </section>
            <section>
                <li>17</li>
                <li>18</li>
                <li>19</li>
                <li>20</li>
                <li>21</li>
                <li>22</li>
                <li>23</li>
            </section>
            <section>
                <li>24</li>
                <li>25</li>
                <li>26</li>
                <li>27</li>
                <li>28</li>
                <li>29</li>
                <li>30</li>
            </section>
        </Fragment>
    )
}